config/routes.rb
Baseviewer::Application.routes.draw do
  resources :links

  resources :wadokus

  resources :kimuras
  resources :comments

  devise_for :users

   get "home/index"
   root :to => 'home#index'

  match 'users/:id/my_kimuras' => 'users#my_kimuras', :as => :users_my_kimura, :via => :get

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :kimura
  attr_accessible :body, :user_id, :kimura_id
end

app/models/kimura.rb
class Kimura < ActiveRecord::Base
  attr_accessible :kimura_column, :kimura_hasCandidates, :kimura_isEdited, :kimura_lemma, :kimura_page, :kimura_reading, :kimura_wadoku_candidates, :kimura_writing
  belongs_to :user
  belongs_to :wadoku
  has_many :comments

  before_save :check_edited

  private

  def check_edited
    self.kimura_isEdited = true if self.wadoku.present?
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :kimura, :student, :wadoku
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :kimuras
  has_many :comments
  # attr_accessible :title, :body
end

app/models/wadoku.rb
class Wadoku < ActiveRecord::Base
  attr_accessible :contents, :entry, :translation, :writing, :reading
  has_one :kimura
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource
  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end

  end
  def after_sign_out_path_for(resource)
     user_session_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :signed_in?
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to @comment.kimura
    end
  end
  def destroy

    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.kimura
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    redirect_to users_my_kimura_path(current_user)
  end
end

app/controllers/kimuras_controller.rb
class KimurasController < ApplicationController
  # GET /kimuras
  # GET /kimuras.json
  before_filter :signed_in?

  def index
    @kimuras = Kimura.order("kimura_page").page(params[:page])
  end

  # GET /kimuras/1
  # GET /kimuras/1.json
  def show
    @kimura = Kimura.find(params[:id])
    @comment = Comment.new
  end

  # GET /kimuras/new
  # GET /kimuras/new.json
  def new
    @kimura = Kimura.new
    @ids = []
    @selected_id = ""
  end

  # GET /kimuras/1/edit
  def edit
    @kimura = Kimura.find(params[:id])
    if current_user == @kimura.user
      @selected_id = @kimura.wadoku ? @kimura.wadoku.entry : ""
      @ids = @kimura.kimura_wadoku_candidates ? @kimura.kimura_wadoku_candidates.split(",").map(&:strip) : []
      @entries = Wadoku.find_all_by_entry(@ids)
      @entries << @kimura.wadoku if @kimura.wadoku.present?
    else
      redirect_to kimuras_path
    end

  end

  # POST /kimuras
  # POST /kimuras.json
  def create
    @kimura = Kimura.new(params[:kimura])
    @kimura.user = current_user
    if @kimura.save
      redirect_to @kimura, :notice => 'Sie haben einen neuen Eintrag erstellt!'
    else
      render :action => "new"
    end
  end

  # PUT /kimuras/1
  # PUT /kimuras/1.json
  def update

    @kimura = Kimura.find(params[:id])
    new_wadoku_contents = params[:kimura].delete("wadoku")

    if params[:wadoku_id] != "new"
      @kimura.wadoku = Wadoku.find_by_entry(params[:wadoku_id])
    else
      @kimura.wadoku = Wadoku.create(entry: 'new', contents: new_wadoku_contents) unless @kimura.wadoku && @kimura.wadoku.entry == 'new'
    end

    if @kimura.update_attributes(params[:kimura])
      redirect_to @kimura, :notice => 'Ihre Eingabe wurde erfolgreich bearbeitet!'
    else
      render :action => "edit"
    end

  end

  # DELETE /kimuras/1
  # DELETE /kimuras/1.json
  def destroy

    @kimura = Kimura.find(params[:id])
    @kimura.destroy

    redirect_to kimuras_url
  end

  private

  def signed_in?
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @links = Link.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, :notice => 'Link was successfully created.' }
        format.json { render :json => @link, :status => :created, :location => @link }
      else
        format.html { render :action => "new" }
        format.json { render :json => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, :notice => 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def my_kimuras
    @kimuras = current_user.kimuras.order("kimura_page").page(params[:page])
  end
end

app/controllers/wadokus_controller.rb
class WadokusController < ApplicationController
  # GET /wadokus
  # GET /wadokus.json
  before_filter :authenticate_user!
  def index
    @wadokus = Wadoku.all
    redirect_to root_path
  end

  # GET /wadokus/1
  # GET /wadokus/1.json
  def show
    @wadoku = Wadoku.find(params[:id])
  end

  # GET /wadokus/new
  # GET /wadokus/new.json
  def new
    @wadoku = Wadoku.new
  end

  # GET /wadokus/1/edit
  def edit
    @wadoku = Wadoku.find(params[:id])
  end

  # POST /wadokus
  # POST /wadokus.json
  def create
    @wadoku = Wadoku.new(params[:wadoku])

    respond_to do |format|
      if @wadoku.save
        format.html { redirect_to @wadoku, :notice => 'Wadoku was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /wadokus/1
  # PUT /wadokus/1.json
  def update
    @wadoku = Wadoku.find(params[:id])

    respond_to do |format|
      if @wadoku.update_attributes(params[:wadoku])
        format.html { redirect_to @wadoku, :notice => 'Wadoku was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /wadokus/1
  # DELETE /wadokus/1.json
  def destroy
    @wadoku = Wadoku.find(params[:id])
    @wadoku.destroy

    respond_to do |format|
      format.html { redirect_to wadokus_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kimuras_helper.rb
module KimurasHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/wadokus_helper.rb
module WadokusHelper
end

app/views/home/index.html.erb
<% if user_signed_in? then %>
<h1>Hallo, <%= current_user.email %>!</h1>
<p><%= link_to "Zur Liste der Einträge aus Kimura", kimuras_path %></p>
<% else %>
<h1>Hallo, Sie sind jetzt nicht (mehr) eingeloggt!</h1>
<% end %>

app/views/kimuras/_form.html.erb
<%= form_for(@kimura) do |f| %>
  <% if @kimura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kimura.errors.count, "error") %> prohibited this kimura from being saved:</h2>

      <ul>
        <% @kimura.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    Seite: <%= "#{@kimura.kimura_page}" %> Spalte: <%= "#{@kimura.kimura_column}" %>
    Lemma: <%= "#{@kimura.kimura_lemma}" %>
  </p>

  <% if @kimura.kimura_isEdited %>
    <p> Dieser Eintrag wurde bereits bearbeitet</p>
  <% else %>
    <p> Dieser Eintrag wurde noch nicht bearbeitet</p>
  <% end %>
  <div class="field">
    <%= f.label "Seite: " %><br />
    <%= f.text_field :kimura_page %>
  </div>
  <div class="field">
    <%= f.label "Spalte: " %><br />
    <%= f.text_field :kimura_column %>
  </div>
  <div class="field">
    <%= f.label "Lemma: " %><br />
    <%= f.text_field :kimura_lemma %>
  </div>

  <div class="field">
    <%= f.label "Lesung: " %><br />
    <%= f.text_field :kimura_reading %>
  </div>
  <div class="field">
    <%= f.label "Schreibung: " %><br />
    <%= f.text_field :kimura_writing %>
  </div>

  <% @entries.each do |wadoku_entry| %>
    <p>
      <span style="color:green"><strong><%= "#{wadoku_entry.entry}"%> </strong></span>
      <br>
      <%="#{wadoku_entry.contents}" %>
    </p>
  <% end %>

  <p>Wählen Sie bitte die passende ID aus der obigen Liste aus: <%= select_tag "wadoku_id", options_for_select(@ids + ['new'], @selected_id) %> </p>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/kimuras/checkCands.html.erb
<h1>Listing candidate-free kimuras</h1>

<%= paginate @kimuras %>

<table>
  <tr>
    <th>Seite</th>
    <th>Spalte</th>
    <th>Lemma</th>
    <th>Lesung</th>
    <th>Bearbeitet</th>
    <th>Kandidaten vorhanden</th>
    <th></th>
    <th></th>
  </tr>

<% @kimuras.each do |kimura| %>
  <tr>
    <td><%= kimura.kimura_page %></td>
    <td><%= kimura.kimura_column %></td>
    <td><%= kimura.kimura_lemma %></td>
    <td><%= kimura.kimura_reading %></td>
    <td><font color="#0000FF"><%= kimura.kimura_isEdited %></font></td>
    <td><%= kimura.kimura_hasCandidates %></td>
    <td><%= link_to 'Show', kimura %></td>
    <td><%= link_to 'Edit', edit_kimura_path(kimura) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/kimuras/edit.html.erb
<h1>Editing kimura</h1>

<%= render 'form' %>




<%= link_to 'Eintrag anzeigen', @kimura %> |
<%= link_to 'Zurück zur Listenansicht', users_my_kimura_path(current_user) %>

app/views/kimuras/index.html.erb
<h1>Listing All Kimura Entries</h1>

<%= paginate @kimuras %>

<table class="table-striped">
  <thead>
    <tr>
      <th>Bearbeiter</th>
      <th>Seite</th>
      <th>Spalte</th>
      <th>Lemma</th>
      <th>Lesung</th>
      <th>Schreibung</th>
      <th>Bearbeitet</th>
      <th>Kommentar</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @kimuras.each do |kimura| %>
      <tr>
        <td><%= kimura.user ? kimura.user.email : "None"%></td>
        <td><%= kimura.kimura_page %></td>
        <td><%= kimura.kimura_column %></td>
        <td><%= kimura.kimura_lemma %></td>
        <td><%= kimura.kimura_reading %></td>
        <td><%= kimura.kimura_writing %></td>
        <td>
          <% if kimura.kimura_isEdited %>
            <span class="label label-success">✓</span> 
          <% end %>
        </td>
        <td>
          <% if kimura.comments.length > 0 %>
            <span class="badge badge-important"><%= kimura.comments.length %></span> 
          <% end %>
        </td>
        <td><%= link_to 'Show', kimura %></td>
        <td>
          <% if kimura.user == current_user %>
            <%= link_to 'Edit', edit_kimura_path(kimura) %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/kimuras/new.html.erb
<h1>New kimura</h1>
<%= form_for(@kimura) do |f| %>
  <% if @kimura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kimura.errors.count, "error") %> prohibited this kimura from being saved:</h2>

      <ul>
        <% @kimura.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Seite: " %><br />
    <%= f.text_field :kimura_page %>
  </div>
  <div class="field">
    <%= f.label "Spalte: " %><br />
    <%= f.text_field :kimura_column %>
  </div>
  <div class="field">
    <%= f.label "Lemma: " %><br />
    <%= f.text_field :kimura_lemma %>
  </div>

  <div class="field">
    <%= f.label "Lesung: " %><br />
    <%= f.text_field :kimura_reading %>
  </div>
  <div class="field">
    <%= f.label "Schreibung: " %><br />
    <%= f.text_field :kimura_writing %>
  </div>


  <p>Wählen Sie bitte die passende ID aus der obigen Liste aus: <%= select_tag "wadoku_id", options_for_select(@ids + ['new'], @selected_id) %> </p>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', users_my_kimura_path(current_user) %>

app/views/kimuras/notAuthorized.html.erb
<h1>Sie haben sich <strong>nicht<strong> eingeloggt</h1>

<p>Bitte wählen Sie eine der folgenden Optionen aus:</p>

<p><%= link_to("Sign in", new_user_session_path) %></p>
<p><%= link_to("Sign up", new_user_registration_path) %></p>

app/views/kimuras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kimura page:</b>
  <%= @kimura.kimura_page %>
</p>

<p>
  <b>Kimura column:</b>
  <%= @kimura.kimura_column %>
</p>

<p>
  <b>Kimura lemma:</b>
  <%= @kimura.kimura_lemma %>
</p>

<p>
  <b>Kimura reading:</b>
  <%= @kimura.kimura_reading %>
</p>

<p>
  <b>Kimura wadoku candidates:</b>
  <%= @kimura.kimura_wadoku_candidates %>
</p>

<% if @kimura.wadoku %>
  <p>
    <b>Kimura parsed wadoku:</b>
    <%= link_to @kimura.wadoku.entry, edit_wadoku_path(@kimura.wadoku) %>
  </p>
<% end %>

<hr>
<ul class="unstyled">
  <% @kimura.comments.order("updated_at DESC").each do |comment| %>
    <li>
    <div name="comment">
      <strong><%= comment.user.email %></strong>
      <br />
      <%= comment.body %>
      <br />
      <%= comment.updated_at.to_s %>
    </div>
    <% if comment.user == current_user %>
      <div class="action">
        <%= link_to "Delete", comment_path(comment), method: :delete %>
      </div>
    <% end %>
    <hr>
    </li>
  <% end%>
</ul>

<%= form_for(Comment.new, :method => :post) do |f| %>                                                              
  <fieldset>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :kimura_id, :value => @kimura.id  %>
    <%= f.hidden_field :user_id, :value => current_user.id  %>
    <%= f.label "Kommentar" %><br />
    <%= f.text_area :body, :class => "comment_field" %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end%>


<%= link_to 'Edit', edit_kimura_path(@kimura) %> |
<%= link_to 'Back to my Kimura entries', users_my_kimura_path(current_user) %> |
<%= link_to 'Back to all entries', kimuras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baseviewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Kimura <3 Wadoku", root_path, :class => 'brand' %>
        <ul class="nav">
          <li><%= link_to "Konto", edit_user_registration_path(current_user), :method => :get %></li>
          <li class="dropdown">
          <a class='dropdown-toggle' data-toggle='dropdown' href='#'>Kimura Entries</a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
            <li><%= link_to "All entries", kimuras_path, :method => :get %></li>
            <li><%= link_to "My entries", users_my_kimura_path(current_user), :method => :get %></li>
          </ul>
          </li>
        </ul>

        <ul class="nav pull-right">
          <li><%= link_to "#{current_user.email} abmelden.", destroy_user_session_path, :method => :delete %></li>
          <li><%= link_to current_user.kimuras.where(:kimura_isEdited => false).length, :url => "#" %></li>
        </ul>
      </div>
    </div>
  </div>..
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="offset2 span9">
        <%= yield %>
      </div>

    </div>
    <hr>
    <footer class="footer">
    <p>Programmierung © 2013 <a href="https://github.com/StasRei">Stanislav Reichert</a></p>
    <p>Source Code bei <a href="https://github.com/thebluber/kimura.git">Github</a></p>
    </footer>
  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baseviewer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= notice %></p>
      <% end %>



      <div class="span12">
      <%= yield %>
      </div>

    </div>
  </div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student %><br />
    <%= f.text_field :student %>
  </div>
  <div class="field">
    <%= f.label :kimura %><br />
    <%= f.text_field :kimura %>
  </div>
  <div class="field">
    <%= f.label :wadoku %><br />
    <%= f.text_field :wadoku %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Kimura</th>
    <th>Wadoku</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.student %></td>
    <td><%= link.kimura %></td>
    <td><%= link.wadoku %></td>
    <td><%= link_to 'Show', link %></td>
    <td><%= link_to 'Edit', edit_link_path(link) %></td>
    <td><%= link_to 'Destroy', link, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @link.student %>
</p>

<p>
  <b>Kimura:</b>
  <%= @link.kimura %>
</p>

<p>
  <b>Wadoku:</b>
  <%= @link.wadoku %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/users/my_kimuras.html.erb
<h1>Listing My Kimura Entries</h1>

<%= paginate @kimuras %>
<%= link_to "Add new kimura", new_kimura_path %>

<table class="table-striped">
  <thead>
    <tr>
      <th>Seite</th>
      <th>Spalte</th>
      <th>Lemma</th>
      <th>Lesung</th>
      <th>Schreibung</th>
      <th>Bearbeitet</th>
      <th>Kommentar</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @kimuras.each do |kimura| %>
      <tr>
        <td><%= kimura.kimura_page %></td>
        <td><%= kimura.kimura_column %></td>
        <td><%= kimura.kimura_lemma %></td>
        <td><%= kimura.kimura_reading %></td>
        <td><%= kimura.kimura_writing %></td>
        <td>
          <% if kimura.kimura_isEdited %>
            <span class="label label-success">✓</span> 
          <% end %>
        </td>
        <td>
          <% if kimura.comments.length > 0 %>
            <span class="badge badge-important"><%= kimura.comments.length %></span> 
          <% end %>
        </td>
        <td><%= link_to 'Show', kimura %></td>
        <td>
          <% if kimura.user == current_user %>
            <%= link_to 'Edit', edit_kimura_path(kimura) %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/wadokus/_form.html.erb
<%= form_for(@wadoku) do |f| %>
  <% if @wadoku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wadoku.errors.count, "error") %> prohibited this wadoku from being saved:</h2>

      <ul>
      <% @wadoku.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry %><br />
    <%= f.text_field :entry %>
  </div>
  <div class="field">
    <strong>Beispiel:</strong>
    <br />
    相対付け (相對付け; 相對づけ)
    <br />
    あいたいづけ
    <br />
    ad. mit gegenseitiger Zustimmung; einmütig; laut gegenseitiger Übereinkunft; im Einverständnis (mit jm.).
  </div>
  <div class="field">
    <%= f.label :contents %><br />
    <%= f.text_area :contents, :style => "width:640px" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wadokus/edit.html.erb
<h1>Editing wadoku</h1>

<%= render 'form' %>

<p><%= link_to 'Zurück zur Liste der Kimura-EInträge', kimuras_path %></p>

app/views/wadokus/index.html.erb
<h1>Listing wadokus</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>Contents</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wadokus.each do |wadoku| %>
  <tr>
    <td><%= wadoku.entry %></td>
    <td><%= wadoku.contents %></td>
    <td><%= link_to 'Show', wadoku %></td>
    <td><%= link_to 'Edit', edit_wadoku_path(wadoku) %></td>
    <td><%= link_to 'Destroy', wadoku, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wadoku', new_wadoku_path %>

app/views/wadokus/new.html.erb
<h1>New wadoku</h1>

<%= render 'form' %>

<%= link_to 'Back', wadokus_path %>

app/views/wadokus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entry:</b>
  <%= @wadoku.entry %>
</p>

<p>
  <b>Contents:</b>
  <%= @wadoku.contents %>
</p>


<%= link_to 'Edit', edit_wadoku_path(@wadoku) %> |
<%= link_to 'Back', wadokus_path %>